language: node_js
sudo: true
dist: trusty

node_js:
  - '6.9.1'

before_script:
  - npm install -g @angular/cli

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

notifications:
  email: false


before_deploy:
  - npm install shelljs
  - node ./create-release.js

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    target_branch: release
    local_dir: release
    on:
      branch: master

  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: binaries/*
    skip_cleanup: true
    branch: master
    on:
      branch: master

branches:
  except:
    - release
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/